import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import NotFound from "@/pages/NotFound";
import { Route, Switch } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";

// Pages
import Home from "./pages/Home";
import About from "./pages/About";
import Contact from "./pages/Contact";
import Blog from "./pages/Blog";
import BlogPost from "./pages/BlogPost";
import DontGetWholesaled from "./pages/DontGetWholesaled";
import DontHireFriendRealtor from "./pages/DontHireFriendRealtor";
import VacantPropertyWarning from "./pages/VacantPropertyWarning";

// Service pages
import ForeclosureHelp from "./pages/services/ForeclosureHelp";
import SecondMortgage from "./pages/services/SecondMortgage";
import RentBack from "./pages/services/RentBack";
import ProbateHomes from "./pages/services/ProbateHomes";
import ProbateRealEstate from "./pages/services/ProbateRealEstate";
import CaliforniaProbateHomeSale from "./pages/CaliforniaProbateHomeSale";
import FastSale from "./pages/services/FastSale";
import BehindOnMortgage from "./pages/services/BehindOnMortgage";
import RoofDamage from "./pages/services/RoofDamage";
import HoarderHouse from "./pages/services/HoarderHouse";
import DivorceHome from "./pages/services/Divorce";
import TiredLandlord from "./pages/services/TiredLandlord";
import JunkRemoval from "./pages/services/JunkRemoval";
import WhyChooseUs from "./pages/WhyChooseUs";
import ArmRateChange from "./pages/services/ArmRateChange";
import CantAffordHome from "./pages/services/CantAffordHome";
import LandlordPortfolioSale from "./pages/services/LandlordPortfolioSale";
import MoldHouse from "./pages/services/MoldHouse";
import FireDamage from "./pages/services/FireDamage";
import CodeViolation from "./pages/services/CodeViolation";
import FoundationProblems from "./pages/services/FoundationProblems";
import MilitaryPCS from "./pages/services/MilitaryPCS";
import FreeOffer from "./pages/FreeOffer";
import Reviews from "./pages/Reviews";
import SeniorSeller from "./pages/services/SeniorSeller";
import ParentsHouse from "./pages/services/ParentsHouse";
import SellMyHouse from "./pages/SellMyHouse";
import SellHouseFastFresno from "./pages/SellHouseFastFresno";
import SellMyHouseFresno from "./pages/SellMyHouseFresno";
import SellMyHouseClovis from "./pages/SellMyHouseClovis";
import SellMyHouseVisalia from "./pages/SellMyHouseVisalia";
import SellMyHouseMadera from "./pages/SellMyHouseMadera";
import SellMyHouseHanford from "./pages/SellMyHouseHanford";
import SellMyHouseKingsburg from "./pages/SellMyHouseKingsburg";
import SellMyHouseKerman from "./pages/SellMyHouseKerman";
import SellMyHouseChowchilla from "./pages/SellMyHouseChowchilla";
import SellHouseAsIsFresno from "./pages/SellHouseAsIsFresno";
import SellMyHouseCashFresno from "./pages/SellMyHouseCashFresno";
import SellInheritedPropertyFresno from "./pages/SellInheritedPropertyFresno";
import HoarderHomeBuyerFresno from "./pages/HoarderHomeBuyerFresno";
import BothOptions from "./pages/BothOptions";
import SellHouseFastClovis from "./pages/SellHouseFastClovis";
import SellHouseFastVisalia from "./pages/SellHouseFastVisalia";
import SellHouseFastBakersfield from "./pages/SellHouseFastBakersfield";
import SellHouseFastTulare from "./pages/SellHouseFastTulare";
import SellHouseFastHub from "./pages/SellHouseFastHub";
import SellHouseFastMadera from "./pages/SellHouseFastMadera";
import CentralValleyHub from "./pages/CentralValleyHub";
import SellHouseFastCentralValley from "./pages/SellHouseFastCentralValley";
import SellHouseFastStockton from "./pages/SellHouseFastStockton";
import SellHouseFastModesto from "./pages/SellHouseFastModesto";
import SanJoaquinCountyHub from "./pages/SanJoaquinCountyHub";
import FresnoHousingMarket from "./pages/FresnoHousingMarket";
import VisaliaHousingMarket from "./pages/VisaliaHousingMarket";
import HowItWorks from "./pages/HowItWorks";
import BeforeAfter from "./pages/BeforeAfter";
import Testimonials from "./pages/Testimonials";
import CashOfferCalculator from "./pages/CashOfferCalculator";

// Google Ads landing pages (no nav, conversion-optimized)
import ArmRateAd from "./pages/ads/ArmRateAd";
import CantAffordAd from "./pages/ads/CantAffordAd";
import ForeclosureAd from "./pages/ads/ForeclosureAd";
import ProbateAd from "./pages/ads/ProbateAd";
import DivorceAd from "./pages/ads/DivorceAd";
import SellFastAd from "./pages/ads/SellFastAd";
import BehindMortgageAd from "./pages/ads/BehindMortgageAd";
import WholesalerWarningAd from "./pages/ads/WholesalerWarningAd";
import LpSeniorSeller from "./pages/lp/SeniorSeller";
import LpDownsize from "./pages/lp/Downsize";

// Fresno neighborhood pages
import FigGarden from "./pages/neighborhoods/FigGarden";
import TowerDistrict from "./pages/neighborhoods/TowerDistrict";
import WoodwardPark from "./pages/neighborhoods/WoodwardPark";
import BullardNeighborhood from "./pages/neighborhoods/Bullard";
import SunnysideNeighborhood from "./pages/neighborhoods/Sunnyside";
import McLaneNeighborhood from "./pages/neighborhoods/McLane";
import OldFigGarden from "./pages/neighborhoods/OldFigGarden";
import CloverleafVillage from "./pages/neighborhoods/CloverleafVillage";
import FigGardenVillage from "./pages/neighborhoods/FigGardenVillage";
import FresnoStateArea from "./pages/neighborhoods/FresnoState";
import NorthFresno from "./pages/neighborhoods/NorthFresno";
import SoutheastFresno from "./pages/neighborhoods/SoutheastFresno";
import ClovisNorth from "./pages/neighborhoods/ClovisNorth";
import FresnoNeighborhoods from "./pages/FresnoNeighborhoods";
import HomeWorth from "./pages/HomeWorth";
import FresnoCashOfferCalculator from "./pages/FreshoCashOfferCalculator";
import SellHouseFastFAQ from "./pages/SellHouseFastFAQ";
import VisaliaNeighborhoods from "./pages/VisaliaNeighborhoods";
import VisaliaNeighborhoodMooneyBlvd from "./pages/visalia-neighborhoods/MooneyBlvd";
import VisaliaNeighborhoodCollegeOfTheSequoias from "./pages/visalia-neighborhoods/CollegeOfTheSequoias";
import VisaliaNeighborhoodGoshenAve from "./pages/visalia-neighborhoods/GoshenAve";
import VisaliaNeighborhoodDinubaAve from "./pages/visalia-neighborhoods/DinubaAve";
import VisaliaNeighborhoodBenMaddox from "./pages/visalia-neighborhoods/BenMaddox";
import VisaliaNeighborhoodDowntownVisalia from "./pages/visalia-neighborhoods/DowntownVisalia";
import VisaliaNeighborhoodMineralKing from "./pages/visalia-neighborhoods/MineralKing";
import VisaliaNeighborhoodCaldwellAve from "./pages/visalia-neighborhoods/CaldwellAve";
import BakersfieldNeighborhoods from "./pages/BakersfieldNeighborhoods";
import BakersfieldNeighborhoodEastBakersfield from "./pages/neighborhoods/EastBakersfield";
import BakersfieldNeighborhoodSouthwestBakersfield from "./pages/neighborhoods/SouthwestBakersfield";
import BakersfieldNeighborhoodOildale from "./pages/neighborhoods/Oildale";
import BakersfieldNeighborhoodKernCity from "./pages/neighborhoods/KernCity";
import BakersfieldNeighborhoodRosedale from "./pages/neighborhoods/Rosedale";
import BakersfieldNeighborhoodDowntownBakersfield from "./pages/neighborhoods/DowntownBakersfield";
import BakersfieldNeighborhoodStockdale from "./pages/neighborhoods/Stockdale";
import BakersfieldNeighborhoodOleanderSunset from "./pages/neighborhoods/OleanderSunset";
// Stockton neighborhood pages
import StocktonNeighborhoods from "./pages/StocktonNeighborhoods";
import StocktonNorthStockton from "./pages/neighborhoods/stockton/north-stockton";
import StocktonSouthStockton from "./pages/neighborhoods/stockton/south-stockton";
import StocktonLincolnVillage from "./pages/neighborhoods/stockton/lincoln-village";
import StocktonWestonRanch from "./pages/neighborhoods/stockton/weston-ranch";
import StocktonBrookside from "./pages/neighborhoods/stockton/brookside";
import StocktonDowntown from "./pages/neighborhoods/stockton/downtown-stockton";
// Modesto neighborhood pages
import ModestoNeighborhoods from "./pages/ModestoNeighborhoods";
import ModestoNorthModesto from "./pages/neighborhoods/modesto/north-modesto";
import ModestoSouthModesto from "./pages/neighborhoods/modesto/south-modesto";
import ModestoVintageFaire from "./pages/neighborhoods/modesto/vintage-faire";
import ModestoSalida from "./pages/neighborhoods/modesto/salida";
import ModestoCeres from "./pages/neighborhoods/modesto/ceres";
import ModestoDowntown from "./pages/neighborhoods/modesto/downtown-modesto";
// City landing pagess
import FresnoPage from "./pages/cities/Fresno";
import ClovisPage from "./pages/cities/Clovis";
import SangerPage from "./pages/cities/Sanger";
import SelmaPage from "./pages/cities/Selma";
import MaderaPage from "./pages/cities/Madera";
import VisaliaPage from "./pages/cities/Visalia";
import HanfordPage from "./pages/cities/Hanford";
import ReedleyPage from "./pages/cities/Reedley";
import BakersfieldPage from "./pages/cities/Bakersfield";
import LemooreePage from "./pages/cities/Lemoore";
import TularePage from "./pages/cities/Tulare";
import PortervillePage from "./pages/cities/Porterville";
import MercedPage from "./pages/cities/Merced";
import StocktonPage from "./pages/cities/Stockton";
import ModestoPage from "./pages/cities/Modesto";
import TurlockPage from "./pages/cities/Turlock";
import KingsCountyPage from "./pages/cities/KingsCounty";
import KingsCountyHub from "./pages/KingsCountyHub";
import SanJoaquinPage from "./pages/cities/SanJoaquin";
import DinubaPage from "./pages/cities/Dinuba";
import FowlerPage from "./pages/cities/Fowler";
import KingsburgPage from "./pages/cities/Kingsburg";
import AvenalPage from "./pages/cities/Avenal";
import CoalingaPage from "./pages/cities/Coalinga";
import TracyPage from "./pages/cities/Tracy";
import LodiPage from "./pages/cities/Lodi";
import MantecaPage from "./pages/cities/Manteca";
import StocktonHousingMarket from "./pages/StocktonHousingMarket";
import ModestoHousingMarket from "./pages/ModestoHousingMarket";
import ReedleyNeighborhoods from "./pages/ReedleyNeighborhoods";
import FresnoCountyHub from "./pages/FresnoCountyHub";
import FresnoRealEstateResources from "./pages/FresnoRealEstateResources";
import ParlierPage from "./pages/cities/Parlier";
import SelmaNeighborhoods from "./pages/SelmaNeighborhoods";
import SangerNeighborhoods from "./pages/SangerNeighborhoods";
import SellHouseFastReedley from "./pages/SellHouseFastReedley";
import SellHouseFastSelma from "./pages/SellHouseFastSelma";
import SellHouseFastSanger from "./pages/SellHouseFastSanger";
import ReedleyHousingMarket from "./pages/ReedleyHousingMarket";
import SelmaHousingMarket from "./pages/SelmaHousingMarket";
import SangerHousingMarket from "./pages/SangerHousingMarket";
import DowntownReedley from "./pages/neighborhoods/reedley/downtown-reedley";
import KingsRiverReedley from "./pages/neighborhoods/reedley/kings-river";
import EastReedley from "./pages/neighborhoods/reedley/east-reedley";
import WestReedley from "./pages/neighborhoods/reedley/west-reedley";
import NorthReedley from "./pages/neighborhoods/reedley/north-reedley";
import DowntownSelma from "./pages/neighborhoods/selma/downtown-selma";
import EastSelma from "./pages/neighborhoods/selma/east-selma";
import WestSelma from "./pages/neighborhoods/selma/west-selma";
import FloralAvenue from "./pages/neighborhoods/selma/floral-avenue";
import DowntownSanger from "./pages/neighborhoods/sanger/downtown-sanger";
import EastSanger from "./pages/neighborhoods/sanger/east-sanger";
import WestSanger from "./pages/neighborhoods/sanger/west-sanger";
import KingsCanyonCorridor from "./pages/neighborhoods/sanger/kings-canyon-corridor";
import SkylineREI from "./pages/SkylineREI";
import FAQPage from "./pages/FAQ";
import GBPTemplates from "./pages/GBPTemplates";
import Resources from "./pages/Resources";
import OrangeCovePage from "./pages/cities/OrangeCove";
import CutlerOrosiPage from "./pages/cities/CutlerOrosi";
import SellHouseFastOrangeCove from "./pages/SellHouseFastOrangeCove";
import SellHouseFastDinuba from "./pages/SellHouseFastDinuba";
import SellHouseFastKingsburg from "./pages/SellHouseFastKingsburg";
import SellHouseFastFowler from "./pages/SellHouseFastFowler";
import StanislausCountyHub from "./pages/StanislausCountyHub";
import SellHouseFastPorterville from "./pages/SellHouseFastPorterville";
import LindsayPage from "./pages/cities/Lindsay";
import ExeterPage from "./pages/cities/Exeter";
import StrathmoreePage from "./pages/cities/Strathmore";
import TulareCountyHub from "./pages/TulareCountyHub";
import PortervilleHousingMarket from "./pages/PortervilleHousingMarket";
import WoodlakePage from "./pages/cities/Woodlake";
import SellHouseFastExeter from "./pages/SellHouseFastExeter";
import SellHouseFastHanford from "./pages/SellHouseFastHanford";
import SellYourHomeFresno from "./pages/SellYourHomeFresno";

function Router() {
  return (
    <Switch>
      <Route path="/" component={Home} />
      <Route path="/about" component={About} />
      <Route path="/contact" component={Contact} />
      <Route path="/blog" component={Blog} />
      <Route path="/blog/:slug" component={BlogPost} />
      <Route path="/faq" component={FAQPage} />
      <Route path="/resources" component={Resources} />
      <Route path="/gbp-post-templates" component={GBPTemplates} />

      {/* Service pages */}
      <Route path="/foreclosure-help" component={ForeclosureHelp} />
      <Route path="/second-mortgage-help" component={SecondMortgage} />
      <Route path="/sell-and-stay-rent-back" component={RentBack} />
      <Route path="/probate-inherited-homes" component={ProbateHomes} />
      <Route path="/probate-real-estate-fresno" component={ProbateRealEstate} />
      <Route path="/california-probate-home-sale" component={CaliforniaProbateHomeSale} />
      <Route path="/sell-house-probate-california" component={CaliforniaProbateHomeSale} />
      <Route path="/how-to-sell-probate-house-california" component={CaliforniaProbateHomeSale} />
      <Route path="/sell-house-fast" component={FastSale} />
      <Route path="/behind-on-mortgage" component={BehindOnMortgage} />
      <Route path="/sell-house-roof-damage" component={RoofDamage} />
      <Route path="/sell-hoarder-house" component={HoarderHouse} />
      <Route path="/sell-house-divorce" component={DivorceHome} />
      <Route path="/tired-landlord" component={TiredLandlord} />
      <Route path="/junk-removal-before-selling" component={JunkRemoval} />
      <Route path="/why-choose-us" component={WhyChooseUs} />
      <Route path="/dont-get-wholesaled" component={DontGetWholesaled} />
      <Route path="/dont-hire-friend-realtor" component={DontHireFriendRealtor} />
      <Route path="/arm-rate-change-help" component={ArmRateChange} />
      <Route path="/cant-afford-my-home" component={CantAffordHome} />
      <Route path="/vacant-property-warning" component={VacantPropertyWarning} />
      <Route path="/sell-rental-portfolio" component={LandlordPortfolioSale} />
      <Route path="/skyline-rei" component={SkylineREI} />
      <Route path="/sell-house-mold" component={MoldHouse} />
      <Route path="/sell-house-fire-damage" component={FireDamage} />
      <Route path="/sell-house-code-violations-fresno" component={CodeViolation} />
      <Route path="/sell-house-foundation-problems" component={FoundationProblems} />
      <Route path="/military-pcs-sell-house" component={MilitaryPCS} />
      <Route path="/free-offer" component={FreeOffer} />
      <Route path="/reviews" component={Reviews} />
      <Route path="/sell-home-retirement-fresno" component={SeniorSeller} />
      <Route path="/sell-parents-house-fresno" component={ParentsHouse} />
      <Route path="/sell-my-house" component={SellMyHouse} />
      <Route path="/sell-my-house-fresno-ca" component={SellMyHouseFresno} />
      <Route path="/sell-my-house-fresno" component={SellMyHouseFresno} />
      <Route path="/sell-my-house-visalia-ca" component={SellMyHouseVisalia} />
      <Route path="/sell-my-house-visalia" component={SellMyHouseVisalia} />
      <Route path="/sell-my-home-visalia" component={SellMyHouseVisalia} />
      <Route path="/sell-house-visalia-ca" component={SellMyHouseVisalia} />
      <Route path="/sell-my-house-clovis-ca" component={SellMyHouseClovis} />
      <Route path="/sell-my-house-clovis" component={SellMyHouseClovis} />
      <Route path="/sell-my-home-clovis" component={SellMyHouseClovis} />
      <Route path="/sell-house-clovis-ca" component={SellMyHouseClovis} />
      <Route path="/sell-my-house-madera-ca" component={SellMyHouseMadera} />
      <Route path="/sell-my-house-madera" component={SellMyHouseMadera} />
      <Route path="/sell-my-home-madera" component={SellMyHouseMadera} />
      <Route path="/sell-house-madera-ca" component={SellMyHouseMadera} />
      <Route path="/sell-my-house-hanford-ca" component={SellMyHouseHanford} />
      <Route path="/sell-my-house-hanford" component={SellMyHouseHanford} />
      <Route path="/sell-my-home-hanford" component={SellMyHouseHanford} />
      <Route path="/sell-house-hanford-ca" component={SellMyHouseHanford} />
      <Route path="/sell-my-house-kingsburg-ca" component={SellMyHouseKingsburg} />
      <Route path="/sell-my-house-kingsburg" component={SellMyHouseKingsburg} />
      <Route path="/sell-my-home-kingsburg" component={SellMyHouseKingsburg} />
      <Route path="/sell-my-house-kerman-ca" component={SellMyHouseKerman} />
      <Route path="/sell-my-house-kerman" component={SellMyHouseKerman} />
      <Route path="/sell-my-home-kerman" component={SellMyHouseKerman} />
      <Route path="/sell-my-house-chowchilla-ca" component={SellMyHouseChowchilla} />
      <Route path="/sell-my-house-chowchilla" component={SellMyHouseChowchilla} />
      <Route path="/sell-my-home-chowchilla" component={SellMyHouseChowchilla} />
      <Route path="/sell-house-as-is-fresno" component={SellHouseAsIsFresno} />
      <Route path="/sell-house-as-is-fresno-ca" component={SellHouseAsIsFresno} />
      <Route path="/sell-my-house-cash-fresno" component={SellMyHouseCashFresno} />
      <Route path="/sell-house-for-cash-fresno" component={SellMyHouseCashFresno} />
      <Route path="/sell-inherited-property-fresno" component={SellInheritedPropertyFresno} />
      <Route path="/sell-inherited-house-fresno" component={SellInheritedPropertyFresno} />
      <Route path="/hoarder-home-buyer-fresno" component={HoarderHomeBuyerFresno} />
      <Route path="/hoarder-house-buyer-fresno" component={HoarderHomeBuyerFresno} />
      <Route path="/sell-home-fresno-options" component={BothOptions} />
      <Route path="/sell-my-home-fresno" component={BothOptions} />
      <Route path="/sell-my-property-fresno" component={BothOptions} />
      <Route path="/sell-home-fresno" component={BothOptions} />
      <Route path="/sell-house-cash-to-investor-fresno" component={BothOptions} />
      <Route path="/sell-house-fresno" component={BothOptions} />
      <Route path="/sell-house-fast-fresno-ca" component={SellHouseFastFresno} />
      <Route path="/sell-house-fast-fresno" component={SellHouseFastFresno} />
      <Route path="/sell-my-house-fast-fresno" component={SellHouseFastFresno} />
      <Route path="/sell-house-fast-clovis-ca" component={SellHouseFastClovis} />
      <Route path="/sell-house-fast-visalia-ca" component={SellHouseFastVisalia} />
      <Route path="/sell-house-fast-bakersfield-ca" component={SellHouseFastBakersfield} />
      <Route path="/sell-house-fast-madera-ca" component={SellHouseFastMadera} />
      <Route path="/sell-house-fast-tulare-ca" component={SellHouseFastTulare} />
      <Route path="/sell-house-fast-stockton-ca" component={SellHouseFastStockton} />
      <Route path="/sell-house-fast-modesto-ca" component={SellHouseFastModesto} />
      <Route path="/san-joaquin-county" component={SanJoaquinCountyHub} />
      <Route path="/we-buy-houses-central-valley" component={CentralValleyHub} />
      <Route path="/sell-house-fast-central-valley" component={SellHouseFastCentralValley} />
      <Route path="/fresno-housing-market" component={FresnoHousingMarket} />
      <Route path="/visalia-housing-market" component={VisaliaHousingMarket} />
      <Route path="/how-it-works" component={HowItWorks} />
      <Route path="/before-after" component={BeforeAfter} />
      <Route path="/testimonials" component={Testimonials} />
      <Route path="/sell-house-fast" component={SellHouseFastHub} />
      <Route path="/cash-offer-calculator" component={CashOfferCalculator} />

      {/* City pages */}
      <Route path="/we-buy-houses-fresno" component={FresnoPage} />
      <Route path="/we-buy-houses-clovis" component={ClovisPage} />
      <Route path="/we-buy-houses-sanger" component={SangerPage} />
      <Route path="/we-buy-houses-selma" component={SelmaPage} />
      <Route path="/we-buy-houses-madera" component={MaderaPage} />
      <Route path="/we-buy-houses-visalia" component={VisaliaPage} />
      <Route path="/we-buy-houses-hanford" component={HanfordPage} />
      <Route path="/sell-house-fast-hanford-ca" component={SellHouseFastHanford} />
      <Route path="/we-buy-houses-reedley" component={ReedleyPage} />
      <Route path="/we-buy-houses-bakersfield" component={BakersfieldPage} />
      <Route path="/we-buy-houses-lemoore" component={LemooreePage} />
      <Route path="/we-buy-houses-tulare" component={TularePage} />
      <Route path="/we-buy-houses-porterville" component={PortervillePage} />
      <Route path="/we-buy-houses-merced" component={MercedPage} />
      <Route path="/we-buy-houses-stockton" component={StocktonPage} />
      <Route path="/we-buy-houses-modesto" component={ModestoPage} />
      <Route path="/we-buy-houses-turlock" component={TurlockPage} />
      <Route path="/we-buy-houses-kings-county" component={KingsCountyPage} />
      <Route path="/kings-county" component={KingsCountyHub} />
      <Route path="/we-buy-houses-san-joaquin-county" component={SanJoaquinPage} />
      <Route path="/we-buy-houses-dinuba" component={DinubaPage} />
      <Route path="/we-buy-houses-parlier" component={ParlierPage} />
      <Route path="/fresno-county" component={FresnoCountyHub} />
      <Route path="/fresno-real-estate-resources" component={FresnoRealEstateResources} />
      <Route path="/we-buy-houses-fowler" component={FowlerPage} />
      <Route path="/we-buy-houses-kingsburg" component={KingsburgPage} />
      <Route path="/we-buy-houses-avenal" component={AvenalPage} />
      <Route path="/we-buy-houses-coalinga" component={CoalingaPage} />
      <Route path="/we-buy-houses-tracy" component={TracyPage} />
      <Route path="/we-buy-houses-lodi" component={LodiPage} />
      <Route path="/we-buy-houses-manteca" component={MantecaPage} />
      <Route path="/stockton-housing-market" component={StocktonHousingMarket} />
      <Route path="/modesto-housing-market" component={ModestoHousingMarket} />

      {/* Google Ads landing pages — no nav, conversion-optimized */}
      <Route path="/lp/arm-rate-change" component={ArmRateAd} />
      <Route path="/lp/cant-afford-home" component={CantAffordAd} />
      <Route path="/lp/stop-foreclosure" component={ForeclosureAd} />
      <Route path="/lp/probate-inherited-home" component={ProbateAd} />
      <Route path="/lp/divorce-home-sale" component={DivorceAd} />
      <Route path="/lp/sell-house-fast" component={SellFastAd} />
      <Route path="/lp/behind-on-mortgage" component={BehindMortgageAd} />
      <Route path="/lp/real-cash-buyer-not-wholesaler" component={WholesalerWarningAd} />
      <Route path="/lp/senior-seller" component={LpSeniorSeller} />
      <Route path="/lp/downsize" component={LpDownsize} />

      {/* Fresno neighborhood pages */}
      <Route path="/fresno-neighborhoods" component={FresnoNeighborhoods} />
      <Route path="/fresno-neighborhoods/fig-garden" component={FigGarden} />
      <Route path="/fresno-neighborhoods/tower-district" component={TowerDistrict} />
      <Route path="/fresno-neighborhoods/woodward-park" component={WoodwardPark} />
      <Route path="/fresno-neighborhoods/bullard" component={BullardNeighborhood} />
      <Route path="/fresno-neighborhoods/sunnyside" component={SunnysideNeighborhood} />
      <Route path="/fresno-neighborhoods/mclane" component={McLaneNeighborhood} />
      <Route path="/fresno-neighborhoods/old-fig-garden" component={OldFigGarden} />
      <Route path="/fresno-neighborhoods/cloverleaf-village" component={CloverleafVillage} />
      <Route path="/fresno-neighborhoods/fig-garden-village" component={FigGardenVillage} />
      <Route path="/fresno-neighborhoods/fresno-state" component={FresnoStateArea} />
      <Route path="/fresno-neighborhoods/north-fresno" component={NorthFresno} />
      <Route path="/fresno-neighborhoods/southeast-fresno" component={SoutheastFresno} />
      <Route path="/fresno-neighborhoods/clovis-north" component={ClovisNorth} />
      {/* Legacy neighborhood routes — redirect via same component */}
      <Route path="/fresno-fig-garden" component={FigGarden} />
      <Route path="/fresno-tower-district" component={TowerDistrict} />
      <Route path="/fresno-woodward-park" component={WoodwardPark} />
      <Route path="/fresno-bullard" component={BullardNeighborhood} />
      <Route path="/fresno-sunnyside" component={SunnysideNeighborhood} />
      <Route path="/fresno-mclane" component={McLaneNeighborhood} />
      <Route path="/fresno-old-fig-garden" component={OldFigGarden} />
      <Route path="/fresno-cloverleaf-village" component={CloverleafVillage} />
      <Route path="/fresno-fig-garden-village" component={FigGardenVillage} />
      <Route path="/fresno-state-area" component={FresnoStateArea} />
      <Route path="/north-fresno" component={NorthFresno} />
      <Route path="/southeast-fresno" component={SoutheastFresno} />
      <Route path="/clovis-north" component={ClovisNorth} />
      {/* Home valuation page */}
      <Route path="/what-is-my-home-worth" component={HomeWorth} />
      <Route path="/fresno-cash-offer-calculator" component={FresnoCashOfferCalculator} />
      <Route path="/sell-house-fast-faq" component={SellHouseFastFAQ} />
      {/* Visalia Neighborhoods */}
      <Route path="/visalia-neighborhoods" component={VisaliaNeighborhoods} />
      <Route path="/visalia-neighborhoods/mooney-blvd" component={VisaliaNeighborhoodMooneyBlvd} />
      <Route path="/visalia-neighborhoods/college-of-the-sequoias" component={VisaliaNeighborhoodCollegeOfTheSequoias} />
      <Route path="/visalia-neighborhoods/goshen-ave" component={VisaliaNeighborhoodGoshenAve} />
      <Route path="/visalia-neighborhoods/dinuba-ave" component={VisaliaNeighborhoodDinubaAve} />
      <Route path="/visalia-neighborhoods/ben-maddox" component={VisaliaNeighborhoodBenMaddox} />
      <Route path="/visalia-neighborhoods/downtown-visalia" component={VisaliaNeighborhoodDowntownVisalia} />
      <Route path="/visalia-neighborhoods/mineral-king" component={VisaliaNeighborhoodMineralKing} />
      <Route path="/visalia-neighborhoods/caldwell-ave" component={VisaliaNeighborhoodCaldwellAve} />
      <Route path="/bakersfield-neighborhoods" component={BakersfieldNeighborhoods} />
      <Route path="/bakersfield-neighborhoods/east-bakersfield" component={BakersfieldNeighborhoodEastBakersfield} />
      <Route path="/bakersfield-neighborhoods/southwest-bakersfield" component={BakersfieldNeighborhoodSouthwestBakersfield} />
      <Route path="/bakersfield-neighborhoods/oildale" component={BakersfieldNeighborhoodOildale} />
      <Route path="/bakersfield-neighborhoods/kern-city" component={BakersfieldNeighborhoodKernCity} />
      <Route path="/bakersfield-neighborhoods/rosedale" component={BakersfieldNeighborhoodRosedale} />
      <Route path="/bakersfield-neighborhoods/downtown-bakersfield" component={BakersfieldNeighborhoodDowntownBakersfield} />
      <Route path="/bakersfield-neighborhoods/stockdale" component={BakersfieldNeighborhoodStockdale} />
      <Route path="/bakersfield-neighborhoods/oleander-sunset" component={BakersfieldNeighborhoodOleanderSunset} />
      {/* Stockton Neighborhoods */}
      <Route path="/stockton-neighborhoods" component={StocktonNeighborhoods} />
      <Route path="/stockton-neighborhoods/north-stockton" component={StocktonNorthStockton} />
      <Route path="/stockton-neighborhoods/south-stockton" component={StocktonSouthStockton} />
      <Route path="/stockton-neighborhoods/lincoln-village" component={StocktonLincolnVillage} />
      <Route path="/stockton-neighborhoods/weston-ranch" component={StocktonWestonRanch} />
      <Route path="/stockton-neighborhoods/brookside" component={StocktonBrookside} />
      <Route path="/stockton-neighborhoods/downtown-stockton" component={StocktonDowntown} />
      {/* Modesto Neighborhoods */}
      <Route path="/modesto-neighborhoods" component={ModestoNeighborhoods} />
      <Route path="/modesto-neighborhoods/north-modesto" component={ModestoNorthModesto} />
      <Route path="/modesto-neighborhoods/south-modesto" component={ModestoSouthModesto} />
      <Route path="/modesto-neighborhoods/vintage-faire" component={ModestoVintageFaire} />
      <Route path="/modesto-neighborhoods/salida" component={ModestoSalida} />
      <Route path="/modesto-neighborhoods/ceres" component={ModestoCeres} />
      <Route path="/modesto-neighborhoods/downtown-modesto" component={ModestoDowntown} />
      {/* Reedley Neighborhoods */}
      <Route path="/reedley-neighborhoods" component={ReedleyNeighborhoods} />
      <Route path="/reedley-neighborhoods/downtown-reedley" component={DowntownReedley} />
      <Route path="/reedley-neighborhoods/kings-river" component={KingsRiverReedley} />
      <Route path="/reedley-neighborhoods/east-reedley" component={EastReedley} />
      <Route path="/reedley-neighborhoods/west-reedley" component={WestReedley} />
      <Route path="/reedley-neighborhoods/north-reedley" component={NorthReedley} />
      {/* Selma Neighborhoods */}
      <Route path="/selma-neighborhoods" component={SelmaNeighborhoods} />
      <Route path="/selma-neighborhoods/downtown-selma" component={DowntownSelma} />
      <Route path="/selma-neighborhoods/east-selma" component={EastSelma} />
      <Route path="/selma-neighborhoods/west-selma" component={WestSelma} />
      <Route path="/selma-neighborhoods/floral-avenue" component={FloralAvenue} />
      {/* Sanger Neighborhoods */}
      <Route path="/sanger-neighborhoods" component={SangerNeighborhoods} />
      <Route path="/sanger-neighborhoods/downtown-sanger" component={DowntownSanger} />
      <Route path="/sanger-neighborhoods/east-sanger" component={EastSanger} />
      <Route path="/sanger-neighborhoods/west-sanger" component={WestSanger} />
      <Route path="/sanger-neighborhoods/kings-canyon-corridor" component={KingsCanyonCorridor} />
      {/* Sell Fast Pages */}
      <Route path="/sell-house-fast-reedley-ca" component={SellHouseFastReedley} />
      <Route path="/sell-house-fast-selma-ca" component={SellHouseFastSelma} />
      <Route path="/sell-house-fast-sanger-ca" component={SellHouseFastSanger} />
      <Route path="/we-buy-houses-orange-cove" component={OrangeCovePage} />
      <Route path="/we-buy-houses-cutler-orosi" component={CutlerOrosiPage} />
      <Route path="/sell-house-fast-orange-cove-ca" component={SellHouseFastOrangeCove} />
      <Route path="/sell-house-fast-dinuba-ca" component={SellHouseFastDinuba} />
      <Route path="/sell-house-fast-kingsburg-ca" component={SellHouseFastKingsburg} />
      <Route path="/sell-house-fast-fowler-ca" component={SellHouseFastFowler} />
      {/* Housing Market Pages */}
      <Route path="/reedley-housing-market" component={ReedleyHousingMarket} />
      <Route path="/selma-housing-market" component={SelmaHousingMarket} />
      <Route path="/sanger-housing-market" component={SangerHousingMarket} />
      <Route path="/stanislaus-county" component={StanislausCountyHub} />
      <Route path="/sell-house-fast-porterville-ca" component={SellHouseFastPorterville} />
      <Route path="/we-buy-houses-lindsay" component={LindsayPage} />
      <Route path="/we-buy-houses-exeter" component={ExeterPage} />
      <Route path="/we-buy-houses-strathmore" component={StrathmoreePage} />
      <Route path="/tulare-county" component={TulareCountyHub} />
      <Route path="/porterville-housing-market" component={PortervilleHousingMarket} />
      <Route path="/we-buy-houses-woodlake" component={WoodlakePage} />
      <Route path="/sell-house-fast-exeter-ca" component={SellHouseFastExeter} />
      <Route path="/sell-your-home-fresno" component={SellYourHomeFresno} />
      <Route path="/sell-my-home-fresno" component={SellYourHomeFresno} />
      <Route path="/buy-my-house-cash-fresno" component={SellYourHomeFresno} />
      <Route path="/404" component={NotFound} />
      <Route component={NotFound} />
    </Switch>
  );
}

function App() {
  return (
    <ErrorBoundary>
      <ThemeProvider defaultTheme="light">
        <TooltipProvider>
          <Toaster />
          <Router />
        </TooltipProvider>
      </ThemeProvider>
    </ErrorBoundary>
  );
}

export default App;
