/**
 * Build-time generator: maps each blog slug to its BlogPostArticles<N>.tsx chunk.
 *
 * Output: client/src/pages/_blogChunkMap.ts exporting SLUG_TO_CHUNK and CHUNK_NUMBERS.
 *
 * Why: BlogPost.tsx currently statically imports all 35 article chunks, producing a
 * single 2.1 MB JS bundle. With this map + dynamic imports, the browser fetches
 * only the chunk containing the requested slug (~40 KB).
 *
 * Slug detection: top-level object keys in each chunk file follow the pattern
 *   ^  "slug-name": (
 * (two-space indent + quoted string + colon + opening paren for the JSX).
 * Anything more deeply indented is JSX content, not a slug entry.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const PAGES_DIR = join(ROOT, "client", "src", "pages");
const OUTPUT = join(PAGES_DIR, "_blogChunkMap.ts");

const CHUNK_FILE_RE = /^BlogPostArticles(\d+)\.tsx$/;
const SLUG_LINE_RE = /^ {2}"([^"]+)":\s*\(/gm;

function main() {
  const files = readdirSync(PAGES_DIR).filter(f => CHUNK_FILE_RE.test(f));
  const slugToChunk: Record<string, number> = {};
  const chunkNumbers: number[] = [];
  let collisions = 0;

  // Iterate chunks in ascending order so later-numbered chunks overwrite earlier ones.
  // This matches BlogPost.tsx, which spreads articleChunk1 → articleChunk36 with later winning.
  const sortedFiles = files.slice().sort((a, b) => {
    return Number(a.match(CHUNK_FILE_RE)![1]) - Number(b.match(CHUNK_FILE_RE)![1]);
  });

  for (const file of sortedFiles) {
    const n = Number(file.match(CHUNK_FILE_RE)![1]);
    chunkNumbers.push(n);
    const src = readFileSync(join(PAGES_DIR, file), "utf-8");
    const slugs: string[] = [];
    for (const m of src.matchAll(SLUG_LINE_RE)) {
      slugs.push(m[1]);
    }
    for (const slug of slugs) {
      if (slug in slugToChunk) {
        collisions++;
        console.warn(`[blog-chunk-map] slug "${slug}" duplicated in BlogPostArticles${slugToChunk[slug]} AND BlogPostArticles${n} — using ${n} (matches BlogPost.tsx spread order)`);
      }
      slugToChunk[slug] = n;
    }
  }

  chunkNumbers.sort((a, b) => a - b);

  const banner = [
    "// AUTO-GENERATED by scripts/generate-blog-chunk-map.ts — do not edit by hand.",
    "// Re-runs on `pnpm prebuild` (and `pnpm sitemap` indirectly via package.json).",
    "",
  ].join("\n");

  const body = [
    `export const SLUG_TO_CHUNK: Record<string, number> = ${JSON.stringify(slugToChunk, null, 2)};`,
    "",
    `export const CHUNK_NUMBERS: readonly number[] = ${JSON.stringify(chunkNumbers)} as const;`,
    "",
  ].join("\n");

  writeFileSync(OUTPUT, banner + body, "utf-8");

  console.log(`[blog-chunk-map] ${Object.keys(slugToChunk).length} slugs across ${chunkNumbers.length} chunks -> ${OUTPUT}`);
  if (collisions > 0) console.warn(`[blog-chunk-map] ${collisions} slug collisions (see warnings above)`);
}

main();
